version: '3'
services:
# PHP-FPM ##############################################
  php-fpm:
    build: ./php-fpm
    volumes:
      - "../myapp/src:/var/www"
    expose:
      - "9000"
    depends_on:
      - mysql
      - redis

# NGINX Server #########################################
  nginx:
    build: ./nginx
    volumes:
      - "../myapp/src:/var/www"
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - php-fpm
# MySQL ################################################
  mysql:
    build: ./mysql
    environment:
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
      - TZ=UTC
    volumes:
      - .data/mysql:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

# Redis ################################################
  redis:
    build: ./redis
    volumes:
      - .data/redis:/data
    ports:
      - "6379:6379"
